### Test
GET http://localhost/api/test

### Register
POST http://localhost/api/register
Content-Type: application/json

{
    "name": "Teszt2 Elek",
    "email": "teszt2@teszt.com",
    "password": "password123"
}

### Login
POST http://localhost/api/login
Content-Type: application/json

{
    "email": "teszt2@teszt.com",
    "password": "password123"
}

### Logout
POST http://localhost/api/logout
Content-Type: application/json
Authorization: Bearer TOKEN_IDE
