### Test
GET http://localhost/api/test

### Register
POST http://localhost/api/register
Content-Type: application/json

{
    "name": "Teszt23 Elek",
    "email": "teszt23@teszt.com",
    "password": "password123"
}

### Login
POST http://localhost/api/login
Content-Type: application/json

{
    "email": "teszt23@teszt.com",
    "password": "password123"
}

### Logout
POST http://localhost/api/logout
Content-Type: application/json
Authorization: Bearer 10|Fj0Juxjb13eQwJZLuUSihTAogNleNypGqpDb6aFU99405e57
